apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-annotation
  labels:
    team: product
    version: 1.0.1
    environment: development
  annotations:
    description: Application of product's team
    application-tags: finance, payment, invoice
spec:
  containers:
    - name: container-nginx
      image: nginx
      ports:
        - containerPort: 80